export const GET_CONTACT = "GET_CONTACT";
export const CREATE_CONTACT = "CREATE_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const SET_CONTACT = "SET_CONTACT";
export const UPDATE_CONTACT = "UPDATE_CONTACT";
export const LOAD_CONTACT = "LOAD_CONTACT";